---
# file: handlers/main.yml
#

- name: restart prometheus
  shell: systemctl daemon-reload; service prometheus stop; service prometheus start
  when: prometheus_use_service|bool

- name: reload prometheus
  shell: systemctl daemon-reload; service prometheus stop; service prometheus start
  when: prometheus_use_service|bool

- name: stop prometheus
  shell: service prometheus stop
  when: prometheus_use_service|bool



- name: restart node_exporter
  shell: systemctl daemon-reload; service node_exporter stop; service node_exporter start
  when: prometheus_use_service|bool

- name: reload node_exporter
  shell: systemctl daemon-reload; service node_exporter stop; service node_exporter start
  when: prometheus_use_service|bool

- name: stop node_exporter
  shell: service node_exporter stop
  when: prometheus_use_service|bool



- name: restart alertmanager
  shell: systemctl daemon-reload; service alertmanager stop; service alertmanager start
  when: prometheus_use_service|bool

- name: reload alertmanager
  shell: systemctl daemon-reload; service alertmanager stop; service alertmanager start
  when: prometheus_use_service|bool

- name: stop alertmanager
  shell: service alertmanager stop;
  when: prometheus_use_service|bool

- name: restart pushgateway
  shell: systemctl daemon-reload; service pushgateway stop; service pushgateway start
  when: prometheus_use_service|bool

- name: reload pushgateway
  shell: systemctl daemon-reload; service pushgateway stop; service pushgateway start
  when: prometheus_use_service|bool

- name: stop pushgateway
  shell: service pushgateway stop;
  when: prometheus_use_service|bool

