---
# file: handlers/main.yml
#

- name: restart prometheus
  shell: pkill -f prometheus; service prometheus start
  when: prometheus_use_service|bool

- name: reload prometheus
  shell: pkill -f prometheus; service prometheus start
  when: prometheus_use_service|bool

- name: stop prometheus
  shell: pkill -f prometheus
  when: prometheus_use_service|bool



- name: restart node_exporter
  shell: pkill -f node_exporter; service node_exporter start
  when: prometheus_use_service|bool

- name: reload node_exporter
  shell: pkill -f node_exporter; service node_exporter start
  when: prometheus_use_service|bool

- name: stop node_exporter
  shell: pkill -f node_exporter
  when: prometheus_use_service|bool



- name: restart alertmanager
  shell: pkill -f alertmanager; service alertmanager start
  when: prometheus_use_service|bool

- name: reload alertmanager
  shell: pkill -f alertmanager; service alertmanager start
  when: prometheus_use_service|bool

- name: stop alertmanager
  shell: pkill -f alertmanager
  when: prometheus_use_service|bool
